
const firebaseConfig={apiKey:"AIzaSyAWhKUn2epbp-N8LSGxJ-ZHmBmBsOLR95U",authDomain:"fir-pen-notes.firebaseapp.com",projectId:"fir-pen-notes",storageBucket:"fir-pen-notes.firebasestorage.app",messagingSenderId:"578440202316",appId:"1:578440202316:web:7eaa8675513f159960cce9"};
let firebaseAuth=null,currentUser=null,firestoreDb=null,firestoreMod=null,cloudBusy=false;
async function setupAuth(){let diag=$("#authDiag");let mark=t=>{if(diag)diag.textContent="v34 • "+t};mark("carregando Firebase");try{let appMod=await import("https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js"),authMod=await import("https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js"),fbApp=appMod.initializeApp(firebaseConfig);firebaseAuth=authMod.getAuth(fbApp);mark("Firebase OK • botão pronto");$("#authMsg").textContent="Entre com sua conta Google para acessar o aplicativo.";$("#googleLogin").onclick=async()=>{mark("clique recebido");try{$("#authMsg").textContent="Abrindo Google…";mark("abrindo Google");let provider=new authMod.GoogleAuthProvider();await authMod.signInWithPopup(firebaseAuth,provider)}catch(e){if(e.code==="auth/popup-blocked"||e.code==="auth/cancelled-popup-request"){let provider=new authMod.GoogleAuthProvider();await authMod.signInWithRedirect(firebaseAuth,provider)}else{mark("erro "+(e.code||"desconhecido"));$("#authMsg").textContent="Erro no login: "+(e.code||e.message||"desconhecido");console.error(e)}}};$("#logoutBtn").onclick=()=>authMod.signOut(firebaseAuth);await authMod.getRedirectResult(firebaseAuth).catch(e=>console.warn("Redirect",e));authMod.onAuthStateChanged(firebaseAuth,async u=>{currentUser=u;updateAuthUI();if(!u)return;await localReady;try{let fireMod=await import("https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js");firestoreMod=fireMod;firestoreDb=fireMod.getFirestore(fbApp);await firstCloudSync()}catch(e){console.error("Firestore init",e);setCloudState("☁ Erro nuvem",e?.message||String(e))}})}catch(e){console.error("Auth init",e);mark("falha ao carregar Firebase");$("#authMsg").textContent="Erro ao carregar login: "+(e.code||e.message||"desconhecido")}}
function updateAuthUI(){let logged=!!currentUser;$("#authGate").classList.toggle("hidden",logged);$("#logoutBtn").classList.toggle("hidden",!logged);$("#userBadge").classList.toggle("hidden",!logged);if(logged){$("#userName").textContent=currentUser.displayName||currentUser.email||"Conta Google";let p=$("#userPhoto");if(currentUser.photoURL){p.src=currentUser.photoURL;p.classList.remove("hidden")}else p.classList.add("hidden");$("#authMsg").textContent="";$("#cloudState").classList.remove("hidden")}else $("#cloudState").classList.add("hidden")}
const $=s=>document.querySelector(s),canvas=$("#canvas"),ctx=canvas.getContext("2d"),base=document.createElement("canvas"),baseCtx=base.getContext("2d");let docs=[],doc=null,tool="pen",drawing=false,current=null,redo=[],penActive=false,saveTimer,lastLiveIndex=0,zoom=1,touches=new Map(),pinchStart=0,pinchZoom=1,touchZoomEnabled=false,lassoPts=[],selectedStrokes=[],lassoDragging=false,lassoLast=null,swipeTouch=null;const DB="spenNotes",STORE="documents";
function openDB(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function get(k){let db=await openDB();return new Promise(ok=>{let r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result)})}
async function put(k,v){let db=await openDB();return new Promise(ok=>{let tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(v,k);tx.oncomplete=ok})}
async function del(k){let db=await openDB();return new Promise(ok=>{let tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(k);tx.oncomplete=ok})}
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2),now=()=>new Date().toISOString();
async function init(){docs=await get("notebooks")||[];let legacy=await get("current");if(legacy&&!docs.length){legacy.id=id();legacy.createdAt=now();legacy.updatedAt=now();legacy.title=legacy.title||"Anotação recuperada";docs=[legacy];await put("notebooks",docs);await del("current")}renderLibrary()}
function fresh(){let t=now();return{id:id(),title:"Nova anotação",paper:"blank",pages:[[]],backgrounds:[],page:0,createdAt:t,updatedAt:t}}

function cloudSafe(n){let c=JSON.parse(JSON.stringify(n));c.backgrounds=(c.backgrounds||[]).map(()=>null);return{id:String(c.id),title:String(c.title||"Sem título"),createdAt:String(c.createdAt||""),updatedAt:String(c.updatedAt||""),payload:JSON.stringify(c)}}
function cloudRestore(r){if(r&&typeof r.payload==="string"){try{let c=JSON.parse(r.payload);if(!Array.isArray(c.pages)||!c.pages.length)c.pages=[[]];c.backgrounds=c.backgrounds||[];return c}catch{}}return{id:r.id,title:r.title||"Sem título",createdAt:r.createdAt||"",updatedAt:r.updatedAt||"",pages:[[]],backgrounds:[],page:0,paper:"blank"}}
function cloudRef(noteId){return firestoreMod.doc(firestoreDb,"users",currentUser.uid,"notebooks",noteId)}
function setCloudState(t,detail=""){let e=$("#cloudState");if(e){e.textContent=t;e.title=detail||t}}
function cloudError(e){let code=(e?.code||"erro").replace(/^firestore\//,""),msg=e?.message||String(e);console.error("Firestore:",code,msg);setCloudState("☁ Erro: "+code,msg)}
function withTimeout(p,ms=15000){return Promise.race([p,new Promise((_,no)=>setTimeout(()=>{let e=new Error("Tempo limite aguardando o Firestore");e.code="cloud-timeout";no(e)},ms))])}
async function pushCloud(n){if(!currentUser||!firestoreDb)return;let c=cloudSafe(n);let bytes=new Blob([JSON.stringify(c)]).size;if(bytes>900000){let e=new Error("Caderno muito grande para um único documento do Firestore ("+Math.round(bytes/1024)+" KB)");e.code="document-too-large";throw e}await withTimeout(firestoreMod.setDoc(cloudRef(n.id),c))}
async function deleteCloud(noteId){if(!currentUser||!firestoreDb)return;try{await firestoreMod.deleteDoc(cloudRef(noteId))}catch(e){console.warn("Cloud delete pending",e)}}
async function firstCloudSync(){if(cloudBusy||!currentUser||!firestoreDb)return;cloudBusy=true;setCloudState("☁ Sincronizando…");try{let failed=[];for(const n of docs){try{await pushCloud(n)}catch(e){failed.push({title:n.title||"Sem título",e})}}if(failed.length){let x=failed[0];cloudError(x.e);$("#cloudState").title=(x.title+" — "+(x.e?.message||x.e));return}let q=firestoreMod.collection(firestoreDb,"users",currentUser.uid,"notebooks"),snap=await withTimeout(firestoreMod.getDocs(q)),changed=false;snap.forEach(ds=>{let r=cloudRestore(ds.data()),i=docs.findIndex(x=>x.id===r.id);if(i<0){docs.push(r);changed=true}else if((r.updatedAt||"")>(docs[i].updatedAt||"")){let localBg=docs[i].backgrounds||[];docs[i]={...r,backgrounds:localBg};changed=true}});if(changed){await put("notebooks",docs);renderLibrary()}setCloudState("☁ Sincronizado")}catch(e){cloudError(e)}finally{cloudBusy=false}}
async function syncOne(n){if(!currentUser||!firestoreDb)return;setCloudState("☁ Sincronizando…");try{await pushCloud(n);setCloudState("☁ Sincronizado")}catch(e){cloudError(e);let el=$("#cloudState");if(el)el.title=(n.title||"Sem título")+" — "+(e?.message||e)}}

async function persist(){if(!doc)return;doc.title=$("#title").value.trim()||"Sem título";doc.paper=$("#paper").value;doc.updatedAt=now();let i=docs.findIndex(x=>x.id===doc.id);if(i>=0)docs[i]=doc;else docs.unshift(doc);$("#status").textContent="Salvando…";await put("notebooks",docs);$("#status").textContent="Salvo";syncOne(doc)}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,200)}
function renderLibrary(){let box=$("#notes");box.innerHTML="";$("#empty").style.display=docs.length?"none":"block";[...docs].sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||"")).forEach(n=>{let el=document.createElement("article");el.className="note";let d=new Date(n.updatedAt||n.createdAt);el.innerHTML="<div><h3></h3><p>"+n.pages.length+" página(s)</p><p>"+d.toLocaleString("pt-BR")+"</p></div><div class='note-actions'><button class='open'>Abrir</button><button class='danger'>Excluir</button></div>";el.querySelector("h3").textContent=n.title;el.querySelector(".open").onclick=()=>{openNote(n.id);enterFullscreen()};el.querySelector(".danger").onclick=async()=>{if(confirm("Excluir esta anotação?")){docs=docs.filter(x=>x.id!==n.id);await put("notebooks",docs);deleteCloud(n.id);renderLibrary()}};box.appendChild(el)})}
function openNote(noteId){doc=docs.find(x=>x.id===noteId);doc.backgrounds=doc.backgrounds||[];doc.page=Math.min(doc.page||0,doc.pages.length-1);$("#title").value=doc.title;$("#paper").value=doc.paper||"blank";$("#library").classList.add("hidden");$("#editor").classList.remove("hidden");redo=[];setTimeout(()=>{resize();info()},0)}
async function enterFullscreen(){try{let el=document.documentElement;if(!document.fullscreenElement){if(el.requestFullscreen)await el.requestFullscreen({navigationUI:"hide"});else if(el.webkitRequestFullscreen)el.webkitRequestFullscreen()}if(screen.orientation?.lock)screen.orientation.lock("landscape").catch(()=>{})}catch{}setTimeout(resize,120)}
$("#fullscreen").onclick=enterFullscreen;
$("#createBtn").onclick=async()=>{let n=fresh();docs.unshift(n);await put("notebooks",docs);syncOne(n);openNote(n.id);enterFullscreen()};$("#back").onclick=async()=>{await persist();doc=null;$("#editor").classList.add("hidden");$("#library").classList.remove("hidden");renderLibrary()};
function resize(){if(!doc)return;let wrap=canvas.parentElement,availW=Math.max(1,wrap.clientWidth-12),availH=Math.max(1,wrap.clientHeight-12),ratio=availW/availH;let w,h;if(ratio>=1){w=availW;h=availH}else{w=availW;h=availH}canvas.dataset.baseW=w;canvas.dataset.baseH=h;applyZoom();let d=devicePixelRatio||1;canvas.width=Math.max(1,Math.round(w*d));canvas.height=Math.max(1,Math.round(h*d));ctx.setTransform(d,0,0,d,0,0);render()}
function logicalSize(){return{w:+canvas.dataset.baseW||canvas.clientWidth,h:+canvas.dataset.baseH||canvas.clientHeight}}
function bg(){let {w,h}=logicalSize();ctx.fillStyle="white";ctx.fillRect(0,0,w,h);let bi=doc.backgrounds?.[doc.page];if(bi?.data){let im=bgImage(bi.data);if(im.complete)drawContained(ctx,im,w,h);}ctx.strokeStyle="#dbeafe";ctx.lineWidth=1;if(doc.paper==="lined"||doc.paper==="grid")for(let y=32;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(doc.paper==="grid")for(let x=32;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}if(doc.paper==="dotted"){ctx.fillStyle="#cbd5e1";for(let y=24;y<h;y+=24)for(let x=24;x<w;x+=24){ctx.beginPath();ctx.arc(x,y,1.2,0,Math.PI*2);ctx.fill()}}if(doc.paper==="checklist"){for(let y=36;y<h;y+=36){ctx.strokeStyle="#cbd5e1";ctx.strokeRect(18,y-10,16,16);ctx.beginPath();ctx.moveTo(48,y+6);ctx.lineTo(w-16,y+6);ctx.stroke()}}}
function drawStroke(s){if(!s?.pts.length)return;ctx.save();ctx.globalAlpha=s.highlighter?.32:1;ctx.strokeStyle=s.eraser?"white":s.color;ctx.lineCap="round";ctx.lineJoin="round";if(s.pts.length===1){let a=s.pts[0];ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(a.x*logicalSize().w,a.y*logicalSize().h,s.size/2,0,Math.PI*2);ctx.fill();return}for(let i=1;i<s.pts.length;i++){let a=s.pts[i-1],b=s.pts[i],p=(a.p+b.p)/2||.5;ctx.lineWidth=s.eraser?s.size*2:s.size*(.55+p*.9);ctx.beginPath();ctx.moveTo(a.x*logicalSize().w,a.y*logicalSize().h);ctx.lineTo(b.x*logicalSize().w,b.y*logicalSize().h);ctx.stroke()}}
function render(){if(!doc)return;bg();doc.pages[doc.page].forEach(drawStroke);drawSelectionOverlay();base.width=canvas.width;base.height=canvas.height;baseCtx.setTransform(1,0,0,1,0,0);baseCtx.clearRect(0,0,base.width,base.height);baseCtx.drawImage(canvas,0,0);if(current)drawStroke(current)}
function drawStrokeOn(c,s,pts){if(!pts?.length)return;let {w,h}=logicalSize();c.save();c.globalAlpha=s.highlighter?.32:1;c.strokeStyle=s.eraser?"white":s.color;c.fillStyle=c.strokeStyle;c.lineCap="round";c.lineJoin="round";if(pts.length===1){let a=pts[0];c.beginPath();c.arc(a.x*w,a.y*h,s.size/2,0,Math.PI*2);c.fill();return}for(let i=1;i<pts.length;i++){let a=pts[i-1],b=pts[i],p=(a.p+b.p)/2||.5;c.lineWidth=s.eraser?s.size*2:s.size*(.55+p*.9);c.beginPath();c.moveTo(a.x*w,a.y*h);c.lineTo(b.x*w,b.y*h);c.stroke()}c.restore()}
function liveRender(){if(!current)return;const KEEP=10;if(current.pts.length-lastLiveIndex>KEEP+12){let cut=current.pts.length-KEEP,pts=current.pts.slice(lastLiveIndex,cut+1),d=devicePixelRatio||1;baseCtx.setTransform(d,0,0,d,0,0);drawStrokeOn(baseCtx,current,pts);lastLiveIndex=cut}ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(base,0,0);let d=devicePixelRatio||1;ctx.setTransform(d,0,0,d,0,0);drawStrokeOn(ctx,current,current.pts.slice(lastLiveIndex))}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pressure||.5,t:Date.now()}}
canvas.onpointerdown=e=>{if(e.pointerType==="touch")return;e.preventDefault();if(e.pointerType==="pen")penActive=true;if(tool==="lasso"){canvas.setPointerCapture(e.pointerId);let p=point(e);if(selectedStrokes.length&&pointInSelection(p)){drawing=true;lassoDragging=true;lassoLast=p;return}selectedStrokes=[];lassoPts=[p];drawing=true;lassoDragging=false;render();return}drawing=true;canvas.setPointerCapture(e.pointerId);if(tool==="eraser"){eraseAt(point(e));return}current={color:$("#color").value,size:+$("#size").value,eraser:false,highlighter:tool==="highlighter",pts:[point(e)]};lastLiveIndex=0;redo=[]};
function penMove(e){if(drawing&&tool==="lasso"){e.preventDefault();let p=point(e);if(lassoDragging&&lassoLast){let dx=p.x-lassoLast.x,dy=p.y-lassoLast.y;selectedStrokes.forEach(s=>s.pts.forEach(q=>{q.x=Math.max(0,Math.min(1,q.x+dx));q.y=Math.max(0,Math.min(1,q.y+dy))}));lassoLast=p;render()}else{lassoPts.push(p);render()}return}if(drawing&&tool==="eraser"){e.preventDefault();let events=e.getCoalescedEvents?e.getCoalescedEvents():[e];events.forEach(v=>eraseAt(point(v)));return}if(!drawing||!current)return;e.preventDefault();let events=e.getCoalescedEvents?e.getCoalescedEvents():[e];events.forEach(v=>current.pts.push(point(v)));liveRender()}
if("onpointerrawupdate"in window)canvas.addEventListener("pointerrawupdate",penMove,{passive:false});else canvas.addEventListener("pointermove",penMove,{passive:false});
function end(e){if(!drawing)return;drawing=false;if(tool==="lasso"){if(lassoDragging){lassoDragging=false;lassoLast=null;queueSave();renderThumbs();render()}else finishLasso();if(e?.pointerType==="pen")setTimeout(()=>penActive=false,300);return}if(current?.pts.length){doc.pages[doc.page].push(current);current=null;render();queueSave()}if(e?.pointerType==="pen")setTimeout(()=>penActive=false,300)}canvas.onpointerup=end;canvas.onpointercancel=end;



function insidePoly(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let a=poly[i],b=poly[j],hit=((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y||1e-9)+a.x);if(hit)inside=!inside}return inside}
function updateSelectionActions(){let el=$("#selectionActions");if(el)el.classList.toggle("hidden",!selectedStrokes.length)}
function finishLasso(){if(lassoPts.length<3){lassoPts=[];selectedStrokes=[];updateSelectionActions();render();return}selectedStrokes=doc.pages[doc.page].filter(s=>s.pts?.some(p=>insidePoly(p,lassoPts)));lassoPts=[];updateSelectionActions();render()}
function selectionBounds(){if(!selectedStrokes.length)return null;let pts=selectedStrokes.flatMap(s=>s.pts||[]),xs=pts.map(p=>p.x),ys=pts.map(p=>p.y);return{x1:Math.min(...xs),y1:Math.min(...ys),x2:Math.max(...xs),y2:Math.max(...ys)}}
function pointInSelection(p){let b=selectionBounds();return b&&p.x>=b.x1-.015&&p.x<=b.x2+.015&&p.y>=b.y1-.015&&p.y<=b.y2+.015}
function drawSelectionOverlay(){let {w,h}=logicalSize();ctx.save();ctx.strokeStyle="#2563eb";ctx.fillStyle="rgba(37,99,235,.08)";ctx.lineWidth=1.5;ctx.setLineDash([6,5]);if(lassoPts.length>1){ctx.beginPath();ctx.moveTo(lassoPts[0].x*w,lassoPts[0].y*h);for(let i=1;i<lassoPts.length;i++)ctx.lineTo(lassoPts[i].x*w,lassoPts[i].y*h);ctx.stroke()}let b=selectionBounds();if(b){ctx.fillRect(b.x1*w,b.y1*h,(b.x2-b.x1)*w,(b.y2-b.y1)*h);ctx.strokeRect(b.x1*w,b.y1*h,(b.x2-b.x1)*w,(b.y2-b.y1)*h)}ctx.restore()}
function clearLasso(){lassoPts=[];selectedStrokes=[];lassoDragging=false;lassoLast=null;updateSelectionActions()}
$("#duplicateSelection").onclick=()=>{if(!selectedStrokes.length)return;let clones=selectedStrokes.map(s=>{let c=structuredClone?structuredClone(s):JSON.parse(JSON.stringify(s));c.pts.forEach(p=>{p.x=Math.min(1,p.x+.025);p.y=Math.min(1,p.y+.025)});return c});doc.pages[doc.page].push(...clones);selectedStrokes=clones;redo=[];updateSelectionActions();render();queueSave();renderThumbs()};
$("#deleteSelection").onclick=()=>{if(!selectedStrokes.length)return;let chosen=new Set(selectedStrokes);doc.pages[doc.page]=doc.pages[doc.page].filter(s=>!chosen.has(s));redo=[];clearLasso();render();queueSave();renderThumbs()};

function applyZoom(){let w=+(canvas.dataset.baseW||canvas.clientWidth||1),h=+(canvas.dataset.baseH||canvas.clientHeight||1);canvas.style.width=(w*zoom)+"px";canvas.style.height=(h*zoom)+"px";let z=$("#zoomInfo");if(z)z.textContent=Math.round(zoom*100)+"%"}
function setZoom(v){zoom=Math.max(.75,Math.min(3,v));applyZoom();render()}
$("#zoomIn").onclick=()=>setZoom(zoom+.25);$("#zoomOut").onclick=()=>setZoom(zoom-.25);$("#zoomReset").onclick=()=>setZoom(1);$("#touchZoom").onclick=()=>{touchZoomEnabled=!touchZoomEnabled;touches.clear();pinchStart=0;let b=$("#touchZoom");b.textContent="Zoom por toque: "+(touchZoomEnabled?"ON":"OFF");b.setAttribute("aria-pressed",touchZoomEnabled);b.classList.toggle("active",touchZoomEnabled)};
canvas.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"&&touchZoomEnabled){touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){let a=[...touches.values()];pinchStart=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);pinchZoom=zoom}}},{passive:false});
canvas.addEventListener("pointermove",e=>{if(!touchZoomEnabled||e.pointerType!=="touch"||!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2&&pinchStart){e.preventDefault();let a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);setZoom(pinchZoom*d/pinchStart)}},{passive:false});

/* v23: one-finger horizontal page swipe; S Pen pipeline remains untouched */
canvas.addEventListener("pointerdown",e=>{if(e.pointerType!=="touch"||touchZoomEnabled||penActive||drawing)return;swipeTouch={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false}}, {passive:true});
canvas.addEventListener("pointermove",e=>{if(!swipeTouch||e.pointerType!=="touch"||e.pointerId!==swipeTouch.id||touchZoomEnabled||penActive){swipeTouch=null;return}swipeTouch.lastX=e.clientX;swipeTouch.lastY=e.clientY;let dx=e.clientX-swipeTouch.x,dy=e.clientY-swipeTouch.y;if(Math.abs(dx)>18||Math.abs(dy)>18)swipeTouch.moved=true;if(Math.abs(dx)>Math.abs(dy)*1.35&&Math.abs(dx)>24)e.preventDefault()}, {passive:false});
function finishPageSwipe(e){if(!swipeTouch||e.pointerId!==swipeTouch.id){return}let s=swipeTouch;swipeTouch=null;if(touchZoomEnabled||penActive||!doc)return;let dx=(s.lastX??e.clientX)-s.x,dy=(s.lastY??e.clientY)-s.y,threshold=Math.max(90,canvas.getBoundingClientRect().width*.12);if(Math.abs(dx)<threshold||Math.abs(dx)<Math.abs(dy)*1.35)return;if(dx<0&&doc.page<doc.pages.length-1)doc.page++;else if(dx>0&&doc.page>0)doc.page--;else return;redo=[];clearLasso();render();info();queueSave()}
canvas.addEventListener("pointerup",finishPageSwipe,{passive:true});canvas.addEventListener("pointercancel",e=>{if(swipeTouch?.id===e.pointerId)swipeTouch=null},{passive:true});

function touchEnd(e){if(e.pointerType==="touch"&&touchZoomEnabled){touches.delete(e.pointerId);if(touches.size<2)pinchStart=0}}canvas.addEventListener("pointerup",touchEnd);canvas.addEventListener("pointercancel",touchEnd);


const imageCache=new Map();function bgImage(src){if(imageCache.has(src))return imageCache.get(src);let im=new Image();im.onload=()=>{if(doc){render();renderThumbs()}};im.src=src;imageCache.set(src,im);return im}
function drawContained(c,im,w,h){let s=Math.min(w/im.naturalWidth,h/im.naturalHeight),dw=im.naturalWidth*s,dh=im.naturalHeight*s;c.drawImage(im,(w-dw)/2,(h-dh)/2,dw,dh)}
function updateImageButton(){let has=!!doc?.backgrounds?.[doc.page]?.data;$("#removeImage")?.classList.toggle("hidden",!has)}
$("#imageBtn").onclick=()=>$("#imageFile").click();
$("#imageFile").onchange=e=>{let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{doc.backgrounds=doc.backgrounds||[];doc.backgrounds[doc.page]={data:r.result,name:f.name};imageCache.delete(r.result);updateImageButton();render();queueSave();renderThumbs()};r.readAsDataURL(f);e.target.value=""};
$("#removeImage").onclick=()=>{if(!doc?.backgrounds?.[doc.page])return;doc.backgrounds[doc.page]=null;updateImageButton();render();queueSave();renderThumbs()};


async function getPdfJs(){if(globalThis.pdfjsLib)return globalThis.pdfjsLib;let m=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");m.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";return m}
$("#pdfImportBtn").onclick=()=>$("#pdfFile").click();
$("#pdfFile").onchange=async e=>{let f=e.target.files?.[0];if(!f)return;$("#status").textContent="Importando PDF…";try{let pdfjs=await getPdfJs(),bytes=new Uint8Array(await f.arrayBuffer()),pdf=await pdfjs.getDocument({data:bytes}).promise,newPages=[],newBgs=[];for(let i=1;i<=pdf.numPages;i++){ $("#status").textContent="PDF "+i+"/"+pdf.numPages;let page=await pdf.getPage(i),vp=page.getViewport({scale:1.6}),c=document.createElement("canvas"),x=c.getContext("2d");c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);x.fillStyle="white";x.fillRect(0,0,c.width,c.height);await page.render({canvasContext:x,viewport:vp}).promise;newPages.push([]);newBgs.push({data:c.toDataURL("image/jpeg",.88),name:f.name+" • "+i})}let replace=doc.pages.length===1&&!doc.pages[0].length&&!doc.backgrounds?.[0];if(replace){doc.pages=newPages;doc.backgrounds=newBgs;doc.page=0}else{let at=doc.page+1;doc.pages.splice(at,0,...newPages);doc.backgrounds=doc.backgrounds||[];while(doc.backgrounds.length<at)doc.backgrounds.push(null);doc.backgrounds.splice(at,0,...newBgs);doc.page=at}redo=[];clearLasso();await persist();resize();info();$("#status").textContent="PDF importado"}catch(err){console.error(err);$("#status").textContent="Erro no PDF";alert("Não foi possível importar este PDF. Verifique sua conexão e tente novamente.")}e.target.value=""};

function eraseAt(p){if(!doc)return;let page=doc.pages[doc.page],r=(+$("#size").value*2+8)/Math.max(logicalSize().w,logicalSize().h),before=page.length;doc.pages[doc.page]=page.filter(s=>!s.pts?.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<r));if(doc.pages[doc.page].length!==before){redo=[];render();queueSave();renderThumbs()}}
function renderThumbs(){let box=$("#pageThumbs");if(!box||!doc)return;box.innerHTML="";doc.pages.forEach((p,i)=>{let b=document.createElement("button");b.className="page-thumb"+(i===doc.page?" active":"");let c=renderPageToCanvas(p,140,190);b.appendChild(c);let s=document.createElement("span");s.textContent="Página "+(i+1);b.appendChild(s);let nav=document.createElement("div");nav.className="thumb-order";let up=document.createElement("button"),down=document.createElement("button");up.textContent="↑";down.textContent="↓";up.disabled=i===0;down.disabled=i===doc.pages.length-1;up.onclick=e=>{e.stopPropagation();movePage(i,i-1)};down.onclick=e=>{e.stopPropagation();movePage(i,i+1)};nav.append(up,down);b.appendChild(nav);b.onclick=()=>{doc.page=i;redo=[];clearLasso();render();info();renderThumbs()};box.appendChild(b)})}
function movePage(from,to){if(to<0||to>=doc.pages.length)return;let p=doc.pages.splice(from,1)[0];doc.pages.splice(to,0,p);if(doc.backgrounds){let b=doc.backgrounds.splice(from,1)[0];doc.backgrounds.splice(to,0,b)}if(doc.page===from)doc.page=to;else if(doc.page===to)doc.page=from;redo=[];render();info();queueSave()}
$("#pagesBtn").onclick=()=>{$("#pagesPanel").classList.toggle("hidden");setTimeout(()=>{resize();renderThumbs()},0)};
document.querySelectorAll("[data-color]").forEach(b=>{b.style.background=b.dataset.color;b.onclick=()=>{$("#color").value=b.dataset.color;tool="pen";document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x.dataset.tool==="pen"))}});
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{if(b.dataset.tool!=="lasso")clearLasso();tool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b))});
$("#undo").onclick=()=>{let p=doc.pages[doc.page];if(p.length){redo.push(p.pop());render();queueSave()}};$("#redo").onclick=()=>{if(redo.length){doc.pages[doc.page].push(redo.pop());render();queueSave()}};
$("#paper").onchange=()=>{doc.paper=$("#paper").value;render();queueSave()};$("#title").oninput=queueSave;$("#newPage").onclick=()=>{doc.pages.push([]);doc.backgrounds=doc.backgrounds||[];doc.backgrounds.push(null);doc.page=doc.pages.length-1;redo=[];clearLasso();render();info();queueSave()};$("#prev").onclick=()=>{if(doc.page>0){doc.page--;redo=[];clearLasso();render();info()}};$("#next").onclick=()=>{if(doc.page<doc.pages.length-1){doc.page++;redo=[];clearLasso();render();info()}};
$("#deletePage").onclick=()=>{if(!confirm("Excluir esta página?"))return;if(doc.pages.length===1)doc.pages[0]=[];else{doc.pages.splice(doc.page,1);if(doc.backgrounds)doc.backgrounds.splice(doc.page,1);doc.page=Math.min(doc.page,doc.pages.length-1)}redo=[];render();info();queueSave()};function info(){$("#pageInfo").textContent=(doc.page+1)+"/"+doc.pages.length;updateImageButton();renderThumbs()}
$("#export").onclick=()=>{render();let a=document.createElement("a");a.download=(doc.title||"anotacao")+"-pagina-"+(doc.page+1)+".png";a.href=canvas.toDataURL("image/png");a.click()};
function renderPageToCanvas(page,w=1240,h=1754,pageIndex=doc.pages.indexOf(page)){let c=document.createElement("canvas"),x=c.getContext("2d");c.width=w;c.height=h;x.fillStyle="white";x.fillRect(0,0,w,h);let bi=doc.backgrounds?.[pageIndex];if(bi?.data){let im=bgImage(bi.data);if(im.complete)drawContained(x,im,w,h)}x.strokeStyle="#dbeafe";x.lineWidth=1.5;if(doc.paper==="lined"||doc.paper==="grid")for(let y=50;y<h;y+=50){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}if(doc.paper==="grid")for(let q=50;q<w;q+=50){x.beginPath();x.moveTo(q,0);x.lineTo(q,h);x.stroke()}for(const s of page){if(!s?.pts?.length)continue;x.strokeStyle=s.eraser?"white":s.color;x.fillStyle=x.strokeStyle;x.lineCap="round";x.lineJoin="round";if(s.pts.length===1){let a=s.pts[0];x.beginPath();x.arc(a.x*w,a.y*h,s.size*.8,0,Math.PI*2);x.fill();continue}for(let i=1;i<s.pts.length;i++){let a=s.pts[i-1],b=s.pts[i],p=(a.p+b.p)/2||.5;x.lineWidth=s.eraser?s.size*3:s.size*1.6*(.55+p*.9);x.beginPath();x.moveTo(a.x*w,a.y*h);x.lineTo(b.x*w,b.y*h);x.stroke()}}return c}
function b64bytes(url){let s=atob(url.split(",")[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function makePdf(images,w,h){let parts=[],offsets=[0],len=0,enc=new TextEncoder(),push=v=>{let b=typeof v==="string"?enc.encode(v):v;parts.push(b);len+=b.length},obj=(n,body)=>{offsets[n]=len;push(n+" 0 obj\n"+body+"\nendobj\n")};push("%PDF-1.4\n");let count=2+images.length*3,kids=[];obj(1,"<< /Type /Catalog /Pages 2 0 R >>");for(let i=0;i<images.length;i++)kids.push((3+i*3)+" 0 R");obj(2,"<< /Type /Pages /Kids ["+kids.join(" ")+"] /Count "+images.length+" >>");images.forEach((img,i)=>{let p=3+i*3,im=p+1,co=p+2,data=b64bytes(img),cmd="q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n";obj(p,"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 "+im+" 0 R >> >> /Contents "+co+" 0 R >>");offsets[im]=len;push(im+" 0 obj\n<< /Type /XObject /Subtype /Image /Width "+w+" /Height "+h+" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+data.length+" >>\nstream\n");push(data);push("\nendstream\nendobj\n");obj(co,"<< /Length "+cmd.length+" >>\nstream\n"+cmd+"endstream")});let xref=len;push("xref\n0 "+(count+1)+"\n0000000000 65535 f \n");for(let i=1;i<=count;i++)push(String(offsets[i]).padStart(10,"0")+" 00000 n \n");push("trailer\n<< /Size "+(count+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF");return new Blob(parts,{type:"application/pdf"})}

function safeName(s){return(s||"caderno").replace(/[\\/:*?"<>|]/g,"-")}
function canvasBlob(c,type="image/png",quality){return new Promise(ok=>c.toBlob(ok,type,quality))}
async function shareFile(file,title){try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title,text:"Compartilhado pelo S Pen Notes",files:[file]});return true}}catch(e){if(e?.name==="AbortError")return true}return false}
$("#sharePage").onclick=async()=>{if(!doc)return;$("#status").textContent="Preparando…";try{let c=renderPageToCanvas(doc.pages[doc.page],1240,1754,doc.page),blob=await canvasBlob(c),file=new File([blob],safeName(doc.title)+"-pagina-"+(doc.page+1)+".png",{type:"image/png"});if(!await shareFile(file,doc.title)){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);alert("O compartilhamento direto não está disponível neste navegador. A imagem foi salva para você compartilhar.")}$("#status").textContent="Salvo"}catch(e){console.error(e);$("#status").textContent="Erro ao compartilhar"}};
async function notebookPdfBlob(){let w=1240,h=1754,imgs=doc.pages.map((p,i)=>renderPageToCanvas(p,w,h,i).toDataURL("image/jpeg",.92));return makePdf(imgs,w,h)}
$("#sharePdf").onclick=async()=>{if(!doc)return;$("#status").textContent="Preparando PDF…";try{await persist();let blob=await notebookPdfBlob(),file=new File([blob],safeName(doc.title)+".pdf",{type:"application/pdf"});if(!await shareFile(file,doc.title)){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);alert("O compartilhamento direto não está disponível neste navegador. O PDF foi salvo para você compartilhar.")}$("#status").textContent="Salvo"}catch(e){console.error(e);$("#status").textContent="Erro ao compartilhar"}};

$("#exportPdf").onclick=async()=>{if(!doc)return;await persist();$("#status").textContent="Gerando PDF…";try{let blob=await notebookPdfBlob(),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=(doc.title||"caderno").replace(/[\\/:*?"<>|]/g,"-")+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);$("#status").textContent="PDF gerado"}catch(e){console.error(e);$("#status").textContent="Erro no PDF";alert("Não foi possível gerar o PDF.")}};
$("#backupBtn").onclick=()=>{let blob=new Blob([JSON.stringify({app:"S Pen Notes",version:2,exportedAt:now(),notebooks:docs})],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="s-pen-notes-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let data=JSON.parse(await f.text());if(!Array.isArray(data.notebooks))throw Error();if(!confirm("Restaurar este backup? As anotações atuais serão substituídas."))return;docs=data.notebooks;await put("notebooks",docs);renderLibrary();alert("Backup restaurado.")}catch{alert("Arquivo de backup inválido.")}e.target.value=""};
document.addEventListener("fullscreenchange",()=>setTimeout(resize,100));addEventListener("resize",resize);
async function clearLegacyPwaCache(){try{if("serviceWorker"in navigator){let regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if("caches"in window){let keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(e){console.warn("Cache cleanup",e)}}
const localReady=init();
setupAuth();
clearLegacyPwaCache();