const $=s=>document.querySelector(s),canvas=$("#canvas"),ctx=canvas.getContext("2d");let docs=[],doc=null,tool="pen",drawing=false,current=null,redo=[],penActive=false,saveTimer;const DB="spenNotes",STORE="documents";
function openDB(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function get(k){let db=await openDB();return new Promise(ok=>{let r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result)})}
async function put(k,v){let db=await openDB();return new Promise(ok=>{let tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(v,k);tx.oncomplete=ok})}
async function del(k){let db=await openDB();return new Promise(ok=>{let tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(k);tx.oncomplete=ok})}
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2),now=()=>new Date().toISOString();
async function init(){docs=await get("notebooks")||[];let legacy=await get("current");if(legacy&&!docs.length){legacy.id=id();legacy.createdAt=now();legacy.updatedAt=now();legacy.title=legacy.title||"Anotação recuperada";docs=[legacy];await put("notebooks",docs);await del("current")}renderLibrary()}
function fresh(){let t=now();return{id:id(),title:"Nova anotação",paper:"blank",pages:[[]],page:0,createdAt:t,updatedAt:t}}
async function persist(){if(!doc)return;doc.title=$("#title").value.trim()||"Sem título";doc.paper=$("#paper").value;doc.updatedAt=now();let i=docs.findIndex(x=>x.id===doc.id);if(i>=0)docs[i]=doc;else docs.unshift(doc);$("#status").textContent="Salvando…";await put("notebooks",docs);$("#status").textContent="Salvo"}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,200)}
function renderLibrary(){let box=$("#notes");box.innerHTML="";$("#empty").style.display=docs.length?"none":"block";[...docs].sort((a,b)=>(b.updatedAt||"").localeCompare(a.updatedAt||"")).forEach(n=>{let el=document.createElement("article");el.className="note";let d=new Date(n.updatedAt||n.createdAt);el.innerHTML="<div><h3></h3><p>"+n.pages.length+" página(s)</p><p>"+d.toLocaleString("pt-BR")+"</p></div><div class='note-actions'><button class='open'>Abrir</button><button class='danger'>Excluir</button></div>";el.querySelector("h3").textContent=n.title;el.querySelector(".open").onclick=()=>openNote(n.id);el.querySelector(".danger").onclick=async()=>{if(confirm("Excluir esta anotação?")){docs=docs.filter(x=>x.id!==n.id);await put("notebooks",docs);renderLibrary()}};box.appendChild(el)})}
function openNote(noteId){doc=docs.find(x=>x.id===noteId);doc.page=Math.min(doc.page||0,doc.pages.length-1);$("#title").value=doc.title;$("#paper").value=doc.paper||"blank";$("#library").classList.add("hidden");$("#editor").classList.remove("hidden");redo=[];setTimeout(()=>{resize();info()},0)}
$("#createBtn").onclick=async()=>{let n=fresh();docs.unshift(n);await put("notebooks",docs);openNote(n.id)};$("#back").onclick=async()=>{await persist();doc=null;$("#editor").classList.add("hidden");$("#library").classList.remove("hidden");renderLibrary()};
function resize(){if(!doc)return;let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);render()}
function bg(){let w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle="white";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#dbeafe";ctx.lineWidth=1;if(doc.paper==="lined"||doc.paper==="grid")for(let y=32;y<h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(doc.paper==="grid")for(let x=32;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}}
function drawStroke(s){if(!s?.pts.length)return;ctx.strokeStyle=s.eraser?"white":s.color;ctx.lineCap="round";ctx.lineJoin="round";if(s.pts.length===1){let a=s.pts[0];ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(a.x*canvas.clientWidth,a.y*canvas.clientHeight,s.size/2,0,Math.PI*2);ctx.fill();return}for(let i=1;i<s.pts.length;i++){let a=s.pts[i-1],b=s.pts[i],p=(a.p+b.p)/2||.5;ctx.lineWidth=s.eraser?s.size*2:s.size*(.55+p*.9);ctx.beginPath();ctx.moveTo(a.x*canvas.clientWidth,a.y*canvas.clientHeight);ctx.lineTo(b.x*canvas.clientWidth,b.y*canvas.clientHeight);ctx.stroke()}}
function render(){if(!doc)return;bg();doc.pages[doc.page].forEach(drawStroke);if(current)drawStroke(current)}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,p:e.pressure||.5,t:Date.now()}}
canvas.onpointerdown=e=>{if(e.pointerType==="touch")return;e.preventDefault();if(e.pointerType==="pen")penActive=true;drawing=true;canvas.setPointerCapture(e.pointerId);current={color:$("#color").value,size:+$("#size").value,eraser:tool==="eraser",pts:[point(e)]};redo=[]};
canvas.onpointermove=e=>{if(!drawing||!current)return;e.preventDefault();(e.getCoalescedEvents?e.getCoalescedEvents():[e]).forEach(v=>current.pts.push(point(v)));render()};
function end(e){if(!drawing)return;drawing=false;if(current?.pts.length){doc.pages[doc.page].push(current);current=null;render();queueSave()}if(e?.pointerType==="pen")setTimeout(()=>penActive=false,300)}canvas.onpointerup=end;canvas.onpointercancel=end;
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b))});
$("#undo").onclick=()=>{let p=doc.pages[doc.page];if(p.length){redo.push(p.pop());render();queueSave()}};$("#redo").onclick=()=>{if(redo.length){doc.pages[doc.page].push(redo.pop());render();queueSave()}};
$("#paper").onchange=()=>{doc.paper=$("#paper").value;render();queueSave()};$("#title").oninput=queueSave;$("#newPage").onclick=()=>{doc.pages.push([]);doc.page=doc.pages.length-1;redo=[];render();info();queueSave()};$("#prev").onclick=()=>{if(doc.page>0){doc.page--;redo=[];render();info()}};$("#next").onclick=()=>{if(doc.page<doc.pages.length-1){doc.page++;redo=[];render();info()}};
$("#deletePage").onclick=()=>{if(!confirm("Excluir esta página?"))return;if(doc.pages.length===1)doc.pages[0]=[];else{doc.pages.splice(doc.page,1);doc.page=Math.min(doc.page,doc.pages.length-1)}redo=[];render();info();queueSave()};function info(){$("#pageInfo").textContent=(doc.page+1)+"/"+doc.pages.length}
$("#export").onclick=()=>{render();let a=document.createElement("a");a.download=(doc.title||"anotacao")+"-pagina-"+(doc.page+1)+".png";a.href=canvas.toDataURL("image/png");a.click()};
function renderPageToCanvas(page,w=1240,h=1754){let c=document.createElement("canvas"),x=c.getContext("2d");c.width=w;c.height=h;x.fillStyle="white";x.fillRect(0,0,w,h);x.strokeStyle="#dbeafe";x.lineWidth=1.5;if(doc.paper==="lined"||doc.paper==="grid")for(let y=50;y<h;y+=50){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}if(doc.paper==="grid")for(let q=50;q<w;q+=50){x.beginPath();x.moveTo(q,0);x.lineTo(q,h);x.stroke()}for(const s of page){if(!s?.pts?.length)continue;x.strokeStyle=s.eraser?"white":s.color;x.fillStyle=x.strokeStyle;x.lineCap="round";x.lineJoin="round";if(s.pts.length===1){let a=s.pts[0];x.beginPath();x.arc(a.x*w,a.y*h,s.size*.8,0,Math.PI*2);x.fill();continue}for(let i=1;i<s.pts.length;i++){let a=s.pts[i-1],b=s.pts[i],p=(a.p+b.p)/2||.5;x.lineWidth=s.eraser?s.size*3:s.size*1.6*(.55+p*.9);x.beginPath();x.moveTo(a.x*w,a.y*h);x.lineTo(b.x*w,b.y*h);x.stroke()}}return c}
function b64bytes(url){let s=atob(url.split(",")[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function makePdf(images,w,h){let parts=[],offsets=[0],len=0,enc=new TextEncoder(),push=v=>{let b=typeof v==="string"?enc.encode(v):v;parts.push(b);len+=b.length},obj=(n,body)=>{offsets[n]=len;push(n+" 0 obj\n"+body+"\nendobj\n")};push("%PDF-1.4\n");let count=2+images.length*3,kids=[];obj(1,"<< /Type /Catalog /Pages 2 0 R >>");for(let i=0;i<images.length;i++)kids.push((3+i*3)+" 0 R");obj(2,"<< /Type /Pages /Kids ["+kids.join(" ")+"] /Count "+images.length+" >>");images.forEach((img,i)=>{let p=3+i*3,im=p+1,co=p+2,data=b64bytes(img),cmd="q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n";obj(p,"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 "+im+" 0 R >> >> /Contents "+co+" 0 R >>");offsets[im]=len;push(im+" 0 obj\n<< /Type /XObject /Subtype /Image /Width "+w+" /Height "+h+" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+data.length+" >>\nstream\n");push(data);push("\nendstream\nendobj\n");obj(co,"<< /Length "+cmd.length+" >>\nstream\n"+cmd+"endstream")});let xref=len;push("xref\n0 "+(count+1)+"\n0000000000 65535 f \n");for(let i=1;i<=count;i++)push(String(offsets[i]).padStart(10,"0")+" 00000 n \n");push("trailer\n<< /Size "+(count+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF");return new Blob(parts,{type:"application/pdf"})}
$("#exportPdf").onclick=async()=>{if(!doc)return;await persist();$("#status").textContent="Gerando PDF…";try{let w=1240,h=1754,imgs=doc.pages.map(p=>renderPageToCanvas(p,w,h).toDataURL("image/jpeg",.92)),blob=makePdf(imgs,w,h),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=(doc.title||"caderno").replace(/[\\/:*?"<>|]/g,"-")+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);$("#status").textContent="PDF gerado"}catch(e){console.error(e);$("#status").textContent="Erro no PDF";alert("Não foi possível gerar o PDF.")}};
$("#backupBtn").onclick=()=>{let blob=new Blob([JSON.stringify({app:"S Pen Notes",version:2,exportedAt:now(),notebooks:docs})],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="s-pen-notes-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let data=JSON.parse(await f.text());if(!Array.isArray(data.notebooks))throw Error();if(!confirm("Restaurar este backup? As anotações atuais serão substituídas."))return;docs=data.notebooks;await put("notebooks",docs);renderLibrary();alert("Backup restaurado.")}catch{alert("Arquivo de backup inválido.")}e.target.value=""};
addEventListener("resize",resize);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");init();